version: "3.3"
   
services:
  scrna_db:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - /Users/mo11/work/app_development/pddata/data:/var/lib/postgresql/data
    env_file: .env    
  scrna_web:
    build: .
    image: mercury/scrna_web_browser:0.126
    command: bash -c "python manage.py makemigrations && python manage.py migrate &&  python manage.py runserver 0.0.0.0:8081"
    ports:
      - "8081:8081"
    volumes:
      - /Users/mo11/work/app_development/media:/app/media
    expose: 
      - "8081"
    depends_on:
      - scrna_db
    env_file: .env
  nginx:
    image: nginx 
    ports: 
      - "443:443"
      - "8080:8080"
    depends_on:
      - scrna_db
      - scrna_web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf



